### ISSUE TITLE
replicate relevant parts of RFD 284 in phbl documentation

### ISSUE THREAD

**Issue by jclulow** [oxidecomputer/phbl#17]
There's a reference to text in RFD 284, which is not public.  We should copy the relevant bits into documentation files in this repository for public consumption.

**Comment by dancrossnyc** [comment]
Were we going to start marking some RFDs public? That might be the simplest solution, but maybe we're not doing that right now. The second simplest may be to just copy RFD 284 into here in its entirety, perhaps with light modification (e.g., remove cross-references to other, non-public RFDs).

**Comment by dancrossnyc** [comment]
RFD 284 is now public, addressing the crux of this issue. Huzzah.
