### ISSUE TITLE
Doesn't boot after 2465c3a8602ef84c18cc196a7a56c49adab135d6

### ISSUE THREAD

**Issue by kc8apf** [oxidecomputer/phbl#33]
Building a Helios image with phbl commit 2465c3a8602ef84c18cc196a7a56c49adab135d6 doesn't boot.  Going back to 2465c3a8602ef84c18cc196a7a56c49adab135d6 (the previous commit on main) boots correctly.

**Comment by dancrossnyc** [comment]
Fixed in 9e73c23b0e97868aad015fc6132ab9d8703c4b5d.
